### PR TITLE
Add -y to add-apt-repository

### PR DESCRIPTION
**Pull request by esteve**
This is useful when running this action via https://github.com/nektos/act to avoid add-apt-repository prompting for confirmation

### CODE REVIEW

**Comment by jspricke** [comment]
Thx and thanks for testing this, feel free to ask if you get stuck. Btw. you can also run the scripts on a normal Debian testing system without the PPA.

**Comment by esteve** [comment]
> @esteve btw. your current job is missing this: https://gitlab.com/autowarefoundation/autoware.auto/autoware_auto_msgs/-/commit/a85138f3f4adcece4fe46bef4ef344dde4a5923d

Good catch, thanks!

**Comment by esteve** [comment]
> @esteve Do you have it working with act already? I am currently setting up something with this as well, but am currently stuck on sbuild failing to setup the chroot environment.

Not yet, I made some progress, but had to add a couple of hacks (missing `/home/runner` or not being writable)

**Comment by jspricke** [comment]
Just for completeness, I don't think it will work in ACT as sbuild needs user namespaces. On the other hand it should be easy to adopt the scripts to run on any Ubuntu 22.04 or Debian testing.

**Pull request merged**
